name: mini-projeto-1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets: 
    - assets/abaixo.png
    - assets/normal.png
    - assets/sobrepeso.png
    - assets/obesoI.png
    - assets/obesoII.png
    - assets/morbido.png
